server:
  port: 9090

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: iam-server
          uri: lb://iam-server
          predicates:
            Path=/iam/**
          filters:
            - BearerToken
            - RefreshToken