version: "3"
services:
  kp45-mysql:
    container_name: kp45-mysql
    image: mysql/mysql-server:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    networks:
      - docker-kp45
    volumes:
        - /data/infrastructure/application/mysql
  kp45-redis:
    container_name: kp45-redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - docker-kp45
networks:
  docker-kp45:
    driver: bridge